### ISSUE TITLE
when class_exists Redis,there is a bug in RedisApi construct

### ISSUE THREAD

**Issue by kcloze** [rolies106/yii-resque#23]
```
PHP Error[2]: Redis::select() expects parameter 1 to be long, string given
    in file /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php at line 35
PHP Error[2]: Redis::select() expects parameter 1 to be long, string given
#0 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php(35):     in file /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php at line 35
Resque_Redis->select()
#1 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php(23): Resque_Redis->establishConnection()
#2 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque.php(66): Resque_Redis->__construct()
#3 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(75): redis()
#4 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(457): all()
#5 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(330): Resque_Worker->pruneDeadWorkers()
#6 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(166): Resque_Worker->startup()
#0 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php(35): #7 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resque(144): Resque_Redis->Resque_Worker->select()
work()
#1 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Redis.php(23): #8 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resque(116): Resque_Redis->startWorker()
establishConnection()
#9 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resqueAct.php(3): #2 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque.php(66): require()
Resque_Redis->__construct()
#3 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(75): redis()
#4 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(457): all()
#5 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(330): Resque_Worker->pruneDeadWorkers()
#6 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/lib/Resque/Worker.php(166): Resque_Worker->startup()
#7 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resque(144): Resque_Worker->work()
#8 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resque(116): startWorker()
#9 /opt/nginx/html/ycf_resque/protected/extensions/yii-resque/bin/resqueAct.php(3): require()
```

I fix it wih below code, the second and the third param should be exchange position.
```
public function __construct($host, $password = null, $database = 0, $timeout = 5)
```

**Comment by kcloze** [comment]
sorry,I find my source code doesn't download from github,close it.
