### ISSUE TITLE
Redis::zRangeByScore() expects at most 4 parameters, 6 given

### ISSUE THREAD

**Issue by serker72** [rolies106/yii-resque#32]
**yiic rresque startrecurring**
PHP Error[2]: Redis::zRangeByScore() expects at most 4 parameters, 6 given
    in file /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/Credis/Client.php at line 608
#0 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/Credis/Client.php(608): Redis->zRangeByScore()
#1 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/Resque/Redis.php(148): Credis_Client->__call()
#2 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/ResqueScheduler.php(246): Resque_Redis->__call()
#3 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/ResqueScheduler/Worker.php(58): nextDelayedTimestamp()
#4 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/lib/ResqueScheduler/Worker.php(43): ResqueScheduler_Worker->handleDelayedItems()
#5 /var/www/projects/rezidenttaxi.loc/protected/components/yii-resque/bin/resque-scheduler(110): ResqueScheduler_Worker->work()

**Comment by jorgegalviscardenas** [comment]
I have the same problem :(

**Comment by jorgegalviscardenas** [comment]
Copy content from Client.php https://github.com/colinmollenhour/credis to yii-resque/components/yii-resque/lib/Credis/Client.php

**Comment by serker72** [comment]
Thank you, problem solved
